[package]
name = "tempmon"
version = "0.2.0"
edition = "2024"

[dependencies]
prometheus = { version = "0.13", default-features = false }
tiny_http = "0.12"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
time = "0.3.44"
